version: '3'

services:
  db:
    container_name: db-mysql
    image: mysql:oracle
    volumes:
      - pruebas-DB:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    restart:  always
    ports:
      - 3306:3306
    

volumes:
  pruebas-DB:
    external: false
      

      

